# -*- coding: utf-8 -*-
"""M23MA2004_A2_PROB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FpxxdItTgxrGiWlaIMmzYB3P-tWf6vD
"""

# !pip install requests beautifulsoup4 wordcloud pdfminer.six PyPDF2

import requests
from bs4 import BeautifulSoup
import PyPDF2
from pdfminer.high_level import extract_text
import re
import io
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from collections import Counter
import pandas as pd
import numpy as np
import torch
import random
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader,random_split
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import torch.nn.functional as F

"""#  DATA PREPARSTION"""

urls=[
    "https://www.iitj.ac.in/mathematics/",
    "https://www.iitj.ac.in/computer-science-engineering/"  ,# department
    "https://www.iitj.ac.in/office-of-academics/en/academic-regulations",   #acadmic regulations
    "https://www.iitj.ac.in/office-of-academics/en/circulars",     # circulars
    "https://www.iitj.ac.in/People/Profile/e9793af3-6d4f-4560-8489-2c256912a72a",  # faculty profile
    "https://www.iitj.ac.in/People/Profile/76c9e7c9-555e-4bb9-82b9-2f5a0ed9d11e",
    "https://www.iitj.ac.in/crf/en/publications",    # Research Pages
    "https://iitj.ac.in/PageImages/Gallery/07-2025/Curriculum-BTech-CSE.pdf",       # BTech CSE Syllabus
    "https://www.iitj.ac.in/PageImages/Gallery/06-2025/M.Tech%20Curriculum_document-2022-07-21-12-37-pm.pdf",  # MTech DCS Syllabus
    "https://www.iitj.ac.in/PageImages/Gallery/06-2025/Minor%20in%20data%20Science_document-2024-05-06-11-01-am.pdf"  #Minor data science Syllabus
]

for i, url in enumerate(urls):

    response = requests.get(url)
    filename = f"doc_{i}.txt"

    if url.endswith(".pdf"):

        pdfs = io.BytesIO(response.content)
        pdf_reader = PyPDF2.PdfReader(pdfs)
        text = ""

        for page in pdf_reader.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text

    else:
        soup = BeautifulSoup(response.text, "html.parser")
        text = soup.get_text()

    with open(filename, "w", encoding="utf-8") as f:
        f.write(text)

print("ALL SAVED")

# merging them into single one

documents=["doc_0.txt","doc_1.txt","doc_2.txt","doc_3.txt","doc_4.txt","doc_5.txt","doc_6.txt","doc_7.txt","doc_8.txt","doc_9.txt"]

with open("DATAset.txt","w",encoding="utf-8") as outfile:
    for doc in documents:
        with open(doc,"r",encoding="utf-8") as infile:
            outfile.write(infile.read())
            outfile.write("\n")


 # removing non english characters

with open("DATAset.txt","r",encoding="utf-8") as f:
    text=f.read()

text=re.sub(r"[^\x00-\x7F]+","",text)

with open("FinalDATAset.txt","w",encoding="utf-8") as f:
    f.write(text)

print("Final DATA CREATED")

# Removal of boilerplate text and formatting artifacts

def remove_boilerplate(text: str) -> str:
  text=re.sub(r"\n+"," ",text)  # multiple newlines 2 single space
  text=re.sub(r"\s+"," ",text)  # spaces/tabs 2 single space
  text=text.strip()             # spaces
  text=re.sub(r"[-_]{2,}"," ",text)  # dashs or underscore
  text=re.sub(r"^[\*\-\*]\s+","",text,flags=re.MULTILINE)  # bullet points
  text=re.sub(r"<[^>]+>","",text) #HTML tags
  text=re.sub(r"http\S+|www.\S+","",text) #urls
  text=re.sub(r"\S+@\S+","",text) #emails
  return text

with open("FinalDATAset.txt","r",encoding="utf-8") as f:
    text=f.read()

new_text=remove_boilerplate(text)

with open("newDATAset.txt","w",encoding="utf-8") as f:
    f.write(new_text)

print("Removal of boilerplate text and formatting artifacts completed")

from typing_extensions import final
#  Removal of excessive punctuation and non-textual content

import re

def remove_pun_txt(text: str) -> str:
    text = re.sub(r"[^\w\s.,!?-]", "", text)   # keep hyphen
    text = re.sub(r"([!?.,])\1+", r"\1", text)
    text = re.sub(r"\s+([.,!?])", r"\1", text)
    return text
with open("newDATAset.txt","r",encoding="utf-8") as f:
    text=f.read()


final_text=remove_pun_txt(text)

with open("finalDATAset.txt","w",encoding="utf-8") as f:
    f.write(final_text)

print("Removal of excessive punctuation and non-textual content completed")

#  Tokenization,Lowercasing

def token_lowercas(text: str) -> str:
  text=text.lower()
  tokens=word_tokenize(text)
  return tokens

with open("finalDATAset.txt","r",encoding="utf-8") as f:
    text=f.read()

processed_text=token_lowercas(text)

with open("CORPUS.txt","w",encoding="utf-8") as f:
    f.write(" ".join(processed_text))
print("Tokenization,Lowercasing Completed")

from collections import Counter

# load processed corpus
with open("CORPUS.txt","r",encoding="utf-8") as f:
    tokens = f.read().split()

# build vocab (NO filtering)
wrd_counter = Counter(tokens)

vocab = {w: i for i, w in enumerate(wrd_counter.keys())}
id2wrd = {i: w for w, i in vocab.items()}

corpus = [vocab[w] for w in tokens]

print("Vocab size:", len(vocab))

# word cloud

with open("CORPUS.txt","r",encoding="utf-8") as f:
    text=f.read()

wordcloud=WordCloud(width=1000,height=800,background_color="white").generate(text)

plt.figure(figsize=(10,8))
plt.imshow(wordcloud)
plt.axis("off")
plt.title("Word Cloud illustrating most frequent words")
plt.show()

print("Top 10 most frequent words")

top_10 = list(wordcloud.words_.items())[:10]

for word, freq in top_10:
    print(f"{word}: {freq:.4f}")

"""# MODEL TRAINING"""

#  NEGATIVE SAMPLING


# Compute probability distribution
word_freq = Counter(tokens)
vocab_words = list(vocab.keys())

freqs = np.array([word_freq[w] for w in vocab_words])
prob = freqs ** 0.75
prob = prob / prob.sum()

def neg_sample(k):
    """
    Sample k negative words based on distribution.
    """
    return np.random.choice(len(vocab_words), size=k, p=prob)

"""CBOW

"""

#  DATASET


class CBOWDataset(Dataset):
    """
    Creates (context, target) pairs for CBOW.
    """
    def __init__(self, corpus, window_size):
        self.data = []

        for i in range(window_size, len(corpus) - window_size):
            context = []

            for j in range(-window_size, window_size + 1):
                if j != 0:
                    context.append(corpus[i + j])

            target = corpus[i]
            self.data.append((context, target))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        x, y = self.data[idx]
        return torch.tensor(x, dtype=torch.long), torch.tensor(y, dtype=torch.long)

#  MODEL (CBOW + NEGATIVE SAMPLING)

class CBOW(nn.Module):
    def __init__(self, vocab_size, embed_dim):
        super().__init__()

        self.in_emb = nn.Embedding(vocab_size, embed_dim)
        self.out_emb = nn.Embedding(vocab_size, embed_dim)

    def forward(self, context, target, negatives):
        """
        context: (batch, context_size)
        target: (batch,)
        negatives: (batch, k)
        """

        # Context embedding
        context_emb = self.in_emb(context)          # (batch, context, dim)

        # Weighted mean (better than simple mean)
        weights = torch.softmax(torch.norm(context_emb, dim=2), dim=1)
        context_vec = torch.sum(context_emb * weights.unsqueeze(2), dim=1)

        # Target embedding
        target_emb = self.out_emb(target)           # (batch, dim)

        # Negative embeddings
        neg_emb = self.out_emb(negatives)           # (batch, k, dim)

        # Positive score
        pos_score = torch.sum(context_vec * target_emb, dim=1)

        # Negative score
        neg_score = torch.bmm(neg_emb, context_vec.unsqueeze(2)).squeeze(2)

        # Loss
        loss = -torch.log(torch.sigmoid(pos_score)) \
               - torch.sum(torch.log(torch.sigmoid(-neg_score)), dim=1)

        return loss.mean()

#  TRAINING FUNCTION


def train_CBOW(model, train_ld, val_ld, vocab_size, epochs, lr, k):

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)

    train_ls = []
    val_ls = []

    for epoch in range(epochs):

        # ===== TRAIN =====
        model.train()
        total_train_loss = 0

        for x, y in train_ld:

            # Generate negative samples
            neg_samples = [neg_sample(k) for _ in range(len(y))]
            neg_samples = torch.tensor(neg_samples, dtype=torch.long)

            optimizer.zero_grad()
            loss = model(x, y, neg_samples)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5)

            optimizer.step()
            total_train_loss += loss.item()

        scheduler.step()

        avg_train_loss = total_train_loss / len(train_ld)
        train_ls.append(avg_train_loss)

        # ===== VALIDATION =====
        model.eval()
        total_val_loss = 0

        with torch.no_grad():
            for x, y in val_ld:

                neg_samples = [neg_sample(k) for _ in range(len(y))]
                neg_samples = torch.tensor(neg_samples, dtype=torch.long)

                loss = model(x, y, neg_samples)
                total_val_loss += loss.item()

        avg_val_loss = total_val_loss / len(val_ld)
        val_ls.append(avg_val_loss)

        print(f"Epoch {epoch+1} | Train: {avg_train_loss:.4f} | Val: {avg_val_loss:.4f}")

    return train_ls, val_ls

#  DATA LOADER


WINDOW_SIZE = 11
dataset = CBOWDataset(corpus, WINDOW_SIZE)

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dt, val_dt = random_split(dataset, [train_size, val_size])

train_ld = DataLoader(train_dt, batch_size=64, shuffle=True)
val_ld   = DataLoader(val_dt, batch_size=64, shuffle=False)



#  TRAIN MODEL


EMBED_DIM = 200
NEG_SAMPLES = 8

model = CBOW(len(vocab), EMBED_DIM)

train_ls, val_ls = train_CBOW(
    model,
    train_ld,
    val_ld,
    vocab_size=len(vocab),
    epochs=15,
    lr=0.001,
    k=NEG_SAMPLES
)

vec = model.in_emb.weight[vocab['semester']]
print("semester -", ", ".join(map(str, vec.tolist())))

#  SIMILARITY FUNCTION


def most_similar(word, model, vocab, id2wrd, top_k=5):

    if word not in vocab:
        return []

    emb = model.in_emb.weight
    word_vec = emb[vocab[word]]

    sims = []

    for i in range(len(vocab)):
        sim = F.cosine_similarity(word_vec, emb[i], dim=0)
        sims.append((id2wrd[i], sim.item()))

    sims.sort(key=lambda x: x[1], reverse=True)

    return sims[1:top_k+1]

#  TEST
words = ["research", "student", "phd", "exam"]

for w in words:
    print(f"\nWord: {w}")
    for word, score in most_similar(w, model, vocab, id2wrd):
        print(f"{word:15} {score:.4f}")

# ANALOGY FUNCTION
import torch.nn.functional as F

def analogy(a, b, c, model, vocab, id2wrd, top_k=5):
    """
    Performs analogy: a : b :: c : ?

    vector = v(b) - v(a) + v(c)
    """

    # Check if words exist
    for word in [a, b, c]:
        if word not in vocab:
            print(f"Word '{word}' not in vocabulary!")
            return []

    emb = model.in_emb.weight

    # Compute analogy vector
    vec = emb[vocab[b]] - emb[vocab[a]] + emb[vocab[c]]

    sims = []

    for i in range(len(vocab)):
        word = id2wrd[i]

        # skip input words
        if word in [a, b, c]:
            continue

        sim = F.cosine_similarity(vec, emb[i], dim=0)
        sims.append((word, sim.item()))

    # sort by similarity
    sims.sort(key=lambda x: x[1], reverse=True)

    return sims[:top_k]


# RUN ANALOGY EXPERIMENTS


analogies = [
    ("ug", "btech", "pg"),            # UG : BTech :: PG : ?
    ("research", "paper", "study"),   # research : paper :: study : ?
    ("student", "school", "phd"),     # student : school :: phd : ?
    ("teacher", "teach", "student"),  # teacher : teach :: student : ?
]

print("\n========== ANALOGY RESULTS ==========\n")

for a, b, c in analogies:
    print(f"{a} : {b} :: {c} : ?")

    results = analogy(a, b, c, model, vocab, id2wrd, top_k=5)

    if len(results) == 0:
        print("No result\n")
        continue

    for word, score in results:
        print(f"{word:15} {score:.4f}")

    print("\n" + "-"*40 + "\n")

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

def plot_pca_cbow(model, vocab, id2wrd, words):
    """
    Perform PCA on selected word embeddings and plot in 2D.
    """

    embeddings = model.in_emb.weight.detach().cpu().numpy()

    # Collect vectors for selected words
    word_vecs = []
    valid_words = []

    for w in words:
        if w in vocab:
            word_vecs.append(embeddings[vocab[w]])
            valid_words.append(w)

    word_vecs = np.array(word_vecs)

    # Apply PCA
    pca = PCA(n_components=2)
    reduced = pca.fit_transform(word_vecs)

    # Plot
    plt.figure(figsize=(8, 6))

    for i, word in enumerate(valid_words):
        x, y = reduced[i]
        plt.scatter(x, y)
        plt.text(x + 0.01, y + 0.01, word, fontsize=10)

    plt.title("PCA Visualization of CBOW Word Embeddings")
    plt.xlabel("PC1")
    plt.ylabel("PC2")
    plt.grid()

    plt.show()

words = [
    # education cluster
    "student", "teacher", "school", "university", "phd",

    # research cluster
    "research", "paper", "study", "analysis",

    # degree cluster
    "ug", "pg", "btech", "mtech", "msc",

    # random unrelated
    "computer", "data", "science"
]
plot_pca_cbow(model, vocab, id2wrd, words)