# -*- coding: utf-8 -*-
"""M23MA2004_A2_PROB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRHJIXyeV_YxpoSVZYvUSfXRNCQxboDC
"""

import matplotlib.pyplot as plt   # For plotting graphs (e.g., training loss)
import random                    # For random sampling (data shuffling, picking names)
import torch                     # Core PyTorch library (tensors, computations)
import torch.nn as nn            # Neural network layers (RNN, LSTM, Linear)
import torch.optim as optim      # Optimizers (Adam, SGD) for training the model

"""#TASK 0"""

# Open the file containing names
# encoding="utf-8"
with open("TrainingNames.txt", "r", encoding="utf-8") as f:

    # Read each line (name), remove spaces/newlines, convert to lowercase
    # Also ignore empty lines
    total_names = [line.strip().lower() for line in f if line.strip()]

# Print total number of names loaded
print("Total Names:", len(total_names))

# Print first 10 names as sample
print("example:", total_names[:10])

# distributions of names
name_length = [len(name) for name in total_names]

plt.figure()
plt.hist(name_length,bins=20)

plt.xlabel('Name Length')
plt.ylabel('Number of Names')
plt.title('Distribution ')
plt.show()

"""# TASK 1"""

# CLEANING DATA
total_names = [n.strip().lower() for n in total_names]
total_names = [n for n in total_names if len(n) >= 4]
total_names = [n for n in total_names if n.isalpha()]

# VOCAB
charc = sorted(set("".join(total_names)))
charc.extend(["^", "~"])

char2num = {ch:i for i,ch in enumerate(charc)}   # char to num mapping
num2char = {i:ch for ch,i in char2num.items()}   # num to char mapping

vocab_size = len(char2num)

print("characters:", charc)

# ENCODING func
def en_names(name):
    return [char2num["^"]] + [char2num[c] for c in name] + [char2num["~"]]

encoded_names = [en_names(n) for n in total_names]

print("encoded_names:", encoded_names[:5])

# Input target pair creation
A, B = [], []

for names in encoded_names:
    if len(names) > 1:
        A.append(names[:-1])
        B.append(names[1:])

# SHUFFLE data
import random
data = list(zip(A, B))
random.shuffle(data)
A, B = zip(*data)
A, B = list(A), list(B)

# train test split
split = int(0.75 * len(A))
train_A, val_A = A[:split], A[split:]
train_B, val_B = B[:split], B[split:]

# training function
import matplotlib.pyplot as plt

def train_names(model, train_A, val_A, train_B, val_B, epochs=20):
    optimzr = torch.optim.Adam(model.parameters(), lr=0.001)
    loss_fn = nn.CrossEntropyLoss()

    train_losses = []
    val_losses = []

    # training loop
    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for a, b in zip(train_A, train_B):
            a = torch.tensor(a).unsqueeze(0)
            b = torch.tensor(b)

            #Forward + Loss + Backprop

            pred = model(a)
            pred = pred.squeeze(0).view(-1, pred.shape[-1])
            b = b.view(-1)

            loss = loss_fn(pred, b)

            optimzr.zero_grad()
            loss.backward()


            torch.nn.utils.clip_grad_norm_(model.parameters(), 5)

            optimzr.step()
            total_loss += loss.item()

        avg_train_loss = total_loss / len(train_A)

        # Validation
        model.eval()
        val_loss = 0

        with torch.no_grad():
            for a, b in zip(val_A, val_B):
                a = torch.tensor(a).unsqueeze(0)
                b = torch.tensor(b)

                pred = model(a)
                pred = pred.squeeze(0).view(-1, pred.shape[-1])
                b = b.view(-1)

                 # Loss Tracking

                loss = loss_fn(pred, b)
                val_loss += loss.item()

        avg_val_loss = val_loss / len(val_A)

        train_losses.append(avg_train_loss)
        val_losses.append(avg_val_loss)

        print(f"Epoch {epoch+1}: Train Loss = {avg_train_loss:.4f}, Val Loss = {avg_val_loss:.4f}")

    #  PLOT
    plt.plot(train_losses, label="Train Loss")
    plt.plot(val_losses, label="Validation Loss")
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.title("Training vs Validation Loss")
    plt.legend()
    plt.show()

    return train_losses, val_losses

# the number of trainable parameters

def param(model):
  total_param=sum(p.numel() for p in model.parameters() if p.requires_grad)
  print(" Trainable Parameters for this model is : ", total_param)

# VANILA RNN


class V_RNN(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()

     # Initialization

    self.embed=nn.Embedding(vocab_size,32)
    self.rnn=nn.RNN(32,128,batch_first=True)
    self.dropout=nn.Dropout(0.1)
    self.fc=nn.Linear(128,vocab_size)

# Forward Pass
  def forward(self,x):
    x=self.embed(x)    # embedding step
    out,_=self.rnn(x)   # RNN Processing
    out= self.dropout(out)    # regularization
    out=self.fc(out)
    return out

v_rnn_model=V_RNN(vocab_size)   # vanila rnn model
train_names(v_rnn_model,train_A,val_A,train_B,val_B)   # model traing
param(v_rnn_model)   # parameter counter

class BiLstm(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()

        # Initialization
        self.embed = nn.Embedding(vocab_size, 64)
        self.lstm = nn.LSTM(64, 48, batch_first=True, bidirectional=True)
        self.dropout = nn.Dropout(0.2)
        self.fc = nn.Linear(96, vocab_size)

       #  Forward pass
    def forward(self, x):
        x = self.embed(x)  # embedding
        out, _ = self.lstm(x)    # BiLSTM Processing
        out = self.dropout(out)   # regularization
        return self.fc(out)

# Training Function

def train_bilstm(model, train_A, val_A, train_B, val_B, epochs=15):
    import torch
    import torch.nn as nn

    optimizer = torch.optim.Adam(model.parameters(), lr=0.0008)

    #  label smoothing
    loss_fn = nn.CrossEntropyLoss(label_smoothing=0.1)

    train_losses = []
    val_losses = []

    best_val = float("inf")

    for epoch in range(epochs):
        #  TRAINING
        model.train()
        total_loss = 0

        for a, b in zip(train_A, train_B):
            a = torch.tensor(a).unsqueeze(0)
            b = torch.tensor(b)

            pred = model(a)
            pred = pred.squeeze(0).view(-1, pred.shape[-1])
            b = b.view(-1)

            loss = loss_fn(pred, b)

            optimizer.zero_grad()
            loss.backward()

            # gradient clipping
            torch.nn.utils.clip_grad_norm_(model.parameters(), 3)

            optimizer.step()
            total_loss += loss.item()

        avg_train = total_loss / len(train_A)

        # VALIDATION
        model.eval()
        val_loss = 0

        with torch.no_grad():
            for a, b in zip(val_A, val_B):
                a = torch.tensor(a).unsqueeze(0)
                b = torch.tensor(b)
                 # Forward + Backprop
                pred = model(a)
                pred = pred.squeeze(0).view(-1, pred.shape[-1])
                b = b.view(-1)

                loss = loss_fn(pred, b)
                val_loss += loss.item()

        avg_val = val_loss / len(val_A)

        train_losses.append(avg_train)
        val_losses.append(avg_val)

        print(f"Epoch {epoch+1}: Train={avg_train:.4f}, Val={avg_val:.4f}")

        #  EARLY STOPPING
        if avg_val < best_val:
            best_val = avg_val
            torch.save(model.state_dict(), "best_bilstm.pth")

    plt.plot(train_losses, label="Train Loss")
    plt.plot(val_losses, label="Validation Loss")
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.title("Training vs Validation Loss")
    plt.legend()
    plt.show()
    return train_losses, val_losses

bilstm_model=BiLstm(vocab_size)  # bilstm model
train_bilstm(bilstm_model,train_A,val_A,train_B,val_B)  # training
param(bilstm_model) # parameter for BILSTM

# RNN with BasicAttentionMechanism

class RNN_B_Attn(nn.Module):
   def __init__(self,vocab_size):
    super().__init__()

    # Initialization
    self.embed=nn.Embedding(vocab_size,32)
    self.rnn=nn.RNN(32,128,batch_first=True)
    self.attn=nn.Linear(128,1)
    self.dropout=nn.Dropout(0.1)
    self.fc=nn.Linear(128,vocab_size)

    # Forward Pass
   def forward(self,x):
     x=self.embed(x)
     out,_=self.rnn(x)

      # Attention Mechanism
     attn_score=self.attn(torch.tanh(out))
     attn_wgt=torch.softmax(self.attn(out),dim=1)
     attn_out=attn_wgt*out
     out=attn_out+out             # Residual Connection
     out=self.dropout(out)

     return self.fc(out)

attn_rnn_model=RNN_B_Attn(vocab_size)   # RNN + Attention Model
train_names(attn_rnn_model,train_A,val_A,train_B,val_B)  # training
param(attn_rnn_model)   # parameter counter

"""#TASK 2

"""

# Name Generation Function for Vanila RNN and RNN with Basic Attention
def gen_names(model, max_len=12, temp=0.9):
    model.eval()
    device = next(model.parameters()).device


    # Token Initialization

    nm = char2num["^"]
    name = [nm]

     # Sequential Generation Loop
    for _ in range(max_len):
        x = torch.tensor(name).unsqueeze(0).to(device)

        with torch.no_grad():
            out = model(x)

        out = out[0, -1]

        prob = torch.softmax(out / temp, dim=0)

        # avoid early stop
        if len(name) < 5:
            prob[char2num["~"]] *=0.3

        # repetition penalty
        if len(name) > 1:
            prob[name[-1]] *= 0.8

        # normalize again
        prob = prob / prob.sum()

        # top-k sampling
        k = 10
        topk_prob, topk_idx = torch.topk(prob, k)
        topk_prob = topk_prob / topk_prob.sum()

        nm = topk_idx[torch.multinomial(topk_prob, 1)].item()

        if num2char[nm] == "~":
            break

        name.append(nm)

    return "".join(num2char[i] for i in name if num2char[i] not in ["^", "~"])

# Name Gen Func for BILSTM
def gen_names_bilstm(model, max_len=12,temp=0.5):
    import torch

    model.eval()

    vowels = set("aeiou")

    def is_valid(name):
        # must contain at least one vowel
        if not any(c in vowels for c in name):
            return False

        # avoid 3+ consonants in a row
        cons = 0
        for c in name:
            if c not in vowels:
                cons += 1
                if cons >= 3:
                    return False
            else:
                cons = 0
        return True

    while True:  # keep generating until valid name
        nm = char2num["^"]
        name = [nm]

        for _ in range(max_len):
            x = torch.tensor(name).unsqueeze(0)

            with torch.no_grad():
                emb = model.embed(x)
                out, _ = model.lstm(emb)

                hidden = model.lstm.hidden_size

                #  forward-only (BiLSTM fix)
                forward = out[:, :, :hidden]
                backward = torch.zeros_like(forward)

                out = torch.cat([forward, backward], dim=2)
                out = model.fc(out)

            out = out[0, -1]

            #  STRONGER SAMPLING
            prob = torch.softmax(out / temp, dim=0)

            # avoid early stop
            if len(name) < 4:
                prob[char2num["~"]] = 0

            # repetition penalty (last 2 chars)
            for token in set(name[-2:]):
                prob[token] *= 0.3

            prob = prob / prob.sum()

            #  tighter top-k
            k = 2
            topk_prob, topk_idx = torch.topk(prob, k)
            topk_prob = topk_prob / topk_prob.sum()

            nm = topk_idx[torch.multinomial(topk_prob, 1)].item()

            if num2char[nm] == "~":
                break

            name.append(nm)

        # decode
        result = "".join(num2char[i] for i in name if num2char[i] not in ["^", "~"])

        #  filter bad names
        if len(result) >= 4 and is_valid(result):
            return result

gen_rnn=[gen_names(v_rnn_model) for _ in range(50)]  # generating names using Vanila RNN
gen_A_RNN=[gen_names(attn_rnn_model) for _ in range(50)]  # generating names using  RNN with atten mechanism

for name in gen_rnn[:10]:
  print(name)

for name in gen_A_RNN[:10]:
  print(name)

# # generating names using  BILSTM

temps = [0.4, 0.45, 0.5]

gen_BiLstm = set()
attempts = 0
max_attempts = 500   # 🔥 safety limit

while len(gen_BiLstm) < 50 and attempts < max_attempts:
    t = random.choice(temps)
    name = gen_names_bilstm(bilstm_model, max_len=12, temp=t)
    gen_BiLstm.add(name)
    attempts += 1

gen_BiLstm = list(gen_BiLstm)

for name in random.sample(gen_BiLstm, min(10, len(gen_BiLstm))):
    print(name)

"""Novelty Rate"""

# Novelty Rate

def novelty_rt(genert,train):
  training=set(train)
  new_names=[nm for nm in genert if nm not in training]
  return len(new_names)/len(genert)

"""Diversity"""

# Diversity

def Diversity(genert):
  return len(set(genert))/len(genert)

"""Metrices"""

# for vanila RNN

print( " Vanila RNN Novelity: ", novelty_rt(gen_rnn,total_names))
print("Vanila RNN Diversity : ",Diversity(gen_rnn))

# for BI  LSTM

print( " BI  LSTM Novelity: ", novelty_rt(gen_BiLstm,total_names))
print("BI  LSTM Diversity : ",Diversity(gen_BiLstm))

# for  RNN with Attention Mechanism

print( " RNN with Attention Mechanism Novelity: ", novelty_rt(gen_A_RNN,total_names))
print("RNN with Attention Mechanism Diversity : ",Diversity(gen_A_RNN))

